name: Renovate Workflow

on:
  push: # Exécute le workflow lorsque tu modifies quelque chose sur une branche
    branches:
      - master
  pull_request: # Exécute le workflow pour les PR ouvertes ou synchronisées
  workflow_dispatch: # Permet de déclencher manuellement le workflow
  schedule:
    - cron : '*/5 * * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Renovate
        uses: renovatebot/github-action@v41.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Utilise le token GitHub pour l'accès
